# **Previsão de Custos Assistenciais e Otimização de Sinistralidade na Saúde Suplementar**

## **Objetivo do Projeto**

* Desenvolvimento de um modelo preditivo de IA e Machine Learning focado na previsão de custos hospitalares (Billing Amount) para otimização do índice de sinistralidade e gestão de risco epidemiológico na saúde suplementar.

### **Informações do Dataset (Dicionário de Dados)**

---

* Dataset sintético contendo 55.500 linhas e 15 colunas, projetado para simular dados reais da área da saúde.
* Cada coluna fornece informações específicas sobre o paciente, sua internação e os serviços de saúde prestados.
* Esta estrutura torna o dataset ideal para tarefas de análise de dados, engenharia de recursos e modelagem preditiva aplicadas ao setor de saúde suplementar e controle de sinistralidade.


| Nome da Coluna | Tipo de Dado | Descrição em Português |
| :--- | :--- | :--- |
| **Name** | object | Nome do paciente associado ao registro de saúde. |
| **Age** | int64 | Idade do paciente no momento da internação, expressa em anos. |
| **Gender** | object | Gênero biológico do paciente. |
| **Blood Type** | object | Tipo sanguíneo do paciente. |
| **Medical Condition** | object | Condição médica principal ou diagnóstico primário do paciente. |
| **Date of Admission** | object | A data em que o paciente foi admitido na unidade de saúde. |
| **Doctor** | object | Nome do médico responsável pelos cuidados do paciente durante a internação. |
| **Hospital** | object | Identifica a instituição de saúde ou hospital onde o paciente foi internado. |
| **Insurance Provider** | object | Operadora de plano de saúde ou provedor de seguro do paciente. |
| **Billing Amount** | float64 | **[Variável Alvo]** O valor total faturado pelos serviços médicos durante a internação. Representa o custo bruto do sinistro. |
| **Room Number** | int64 | Número do quarto/leito onde o paciente ficou acomodado. |
| **Admission Type** | object | Especifica o caráter da internação, refletindo as circunstâncias da admissão. |
| **Discharge Date** | object | A data em que o paciente recebeu alta hospitalar. |
| **Medication** | object | Identifica o medicamento principal prescrito ou administrado durante a internação. |
| **Test Results** | object | Descreve o resultado dos exames médicos diagnósticos realizados. |

## **Leitura do Arquivo e Análise Inicial dos Dados**

In [ ]:
# importar as bibliotecas

import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# carregar o arquivo .csv e analisar seus componentes

try:
    df = pd.read_csv('healthcare_dataset.csv')
    print(f"✅ Arquivo carregado com sucesso!")
    print('=' * 55)
    print(f"🔍 Visualização das Primeiras Linhas do Dataframe")
    print('=' * 55)
    display(df.head())
    print('=' * 45)
    print(f"ℹ️ Informações do Dataframe")
    print('=' * 45)
    print(df.info())
    print('=' * 45)
    print(f"📊 Estatísticas Descritivas do Dataframe")
    print('=' * 45)
    print(df.describe())
    print('=' * 45)
    print(f"📐 Dimensões do DataFrame")
    print('=' * 45)
    print(f"Número de Linhas: {df.shape[0]}")
    print(f"Número de Colunas: {df.shape[1]}")
except Exception as e:
    print(f"❌ Erro ao ler o arquivo. Detalhes: {e}")

✅ Arquivo carregado com sucesso!
=======================================================
🔍 Visualização das Primeiras Linhas do Dataframe
=======================================================

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

=============================================
ℹ️ Informações do Dataframe
=============================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB
None
=============================================
📊 Estatísticas Descritivas do Dataframe
=============================================
                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000
=============================================
📐 Dimensões do DataFrame
=============================================
Número de Linhas: 55500
Número de Colunas: 15

In [ ]:
# cópia do dataframe original antes da manipulação para segurança
df_original = df.copy()

In [ ]:
# === ANÁLISE E TRATAMENTO INICIAL DOS DADOS ===

# --- 1. Padronização da Nomenclatura das Colunas do Dataframe ---
df.columns = df.columns.str.lower().str.replace(' ','_')
print("✅ Padronização da Nomenclatura das Colunas Concluída\n" + '=' * 65)
print(list(df.columns))
print()

# --- 2. Padronização da Coluna 'name' ---
print("✅ Padronização da Colunas 'name' Concluída\n" + '=' * 65)
print(f"* Antes: {df_original['Name'].head(3).tolist()}")
df['name'] = df['name'].str.lower()
print(f"* Depois: {df['name'].head(3).tolist()}")
print()

# --- 3. Transformar as Colunas 'date_of_admission' e 'discharge_date' para Datetima ---
print("✅ Adequação do Tipo de Dados Concluída\n" + '=' * 65)
df['date_of_admission'] = pd.to_datetime(df['date_of_admission'], errors='coerce')
df['discharge_date'] = pd.to_datetime(df['discharge_date'], errors='coerce')
print(f"* Tipagem da Coluna 'date_of_admission': {df['date_of_admission'].dtype}")
print(f"* Tipagem da Coluna 'discharge_date': {df['discharge_date'].dtype}")
print()

# --- 4. Arredondar Valor de 'billing_amount' ---
print("✅ Valor Arredondado .2f para 'billing_amount' Concluída\n" + '=' * 65)
df['billing_amount'] = df['billing_amount'].round(2)
print(df['billing_amount'].head().tolist())
print()

# --- 5. Checagem de Valores Nulos e Duplicados
print("✅ Conferência de Valores Nulos e Duplicados Concluída\n" + '=' * 65)
df_nulos = df.isna().sum().sum()
df_duplicados = df.duplicated().sum()
print(f"Valores Nulos: {df_nulos}")
print(f"Valores Duplicados: {df_duplicados}")

✅ Padronização da Nomenclatura das Colunas Concluída
=================================================================
['name', 'age', 'gender', 'blood_type', 'medical_condition', 'date_of_admission', 'doctor', 'hospital', 'insurance_provider', 'billing_amount', 'room_number', 'admission_type', 'discharge_date', 'medication', 'test_results']

✅ Padronização da Colunas 'name' Concluída
=================================================================
* Antes: ['Bobby JacksOn', 'LesLie TErRy', 'DaNnY sMitH']
* Depois: ['bobby jackson', 'leslie terry', 'danny smith']

✅ Adequação do Tipo de Dados Concluída
=================================================================
* Tipagem da Coluna 'date_of_admission': datetime64[ns]
* Tipagem da Coluna 'discharge_date': datetime64[ns]

✅ Valor Arredondado .2f para 'billing_amount' Concluída
=================================================================
[18856.28, 33643.33, 27955.1, 37909.78, 14238.32]

✅ Conferência de Valores Nulos e Duplicados Concluída
=================================================================
Valores Nulos: 0
Valores Duplicados: 534

In [ ]:
# === ANÁLISE DOS VALORES DUPLICADOS (534) ===

# --- 1. Visualização das linhas 100% duplicadas isoladas
print("🔍 Análise da amostra de linhas 100% idênticas (Possível erro de sistema):")
print('=' * 75)
# Filtra apenas as linhas duplicadas e ordena pelo nome do paciente
df_duplicados_completos = df[df.duplicated(keep=False)].sort_values(by='name')
display(df_duplicados_completos.head(6))
print()

# --- 2. Remoção dos valores duplicados exatos do Dataframe ---

df = df_duplicados_completos.drop_duplicates()
print("✅ Conferência de Valores Nulos e Duplicados Concluída\n" + '=' * 65)
print(f"* Quantidade de Linhas Duplicadas: {df_duplicados}")
print(f"* Novo formato do Dataframe após .drop: {df.shape[0]} linhas")

🔍 Análise da amostra de linhas 100% idênticas (Possível erro de sistema):
===========================================================================

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
42407,abigail young,41,Female,O+,Hypertension,2022-12-15,Edward Kramer,Moore-Mcdaniel,UnitedHealthcare,1983.57,192,Elective,2023-01-13,Ibuprofen,Normal
54285,abigail young,41,Female,O+,Hypertension,2022-12-15,Edward Kramer,Moore-Mcdaniel,UnitedHealthcare,1983.57,192,Elective,2023-01-13,Ibuprofen,Normal
40385,adam thomas,75,Male,O+,Hypertension,2022-01-02,Beverly Miller,Sanchez-Wilson,Cigna,16294.91,180,Urgent,2022-01-30,Ibuprofen,Normal
53139,adam thomas,75,Male,O+,Hypertension,2022-01-02,Beverly Miller,Sanchez-Wilson,Cigna,16294.91,180,Urgent,2022-01-30,Ibuprofen,Normal
55298,alex black,51,Male,O+,Diabetes,2022-03-27,Frank Williams,Short and Sons,Aetna,39525.67,246,Emergency,2022-04-21,Aspirin,Normal
24779,alex black,51,Male,O+,Diabetes,2022-03-27,Frank Williams,Short and Sons,Aetna,39525.67,246,Emergency,2022-04-21,Aspirin,Normal

✅ Conferência de Valores Nulos e Duplicados Concluída
=================================================================
* Quantidade de Linhas Duplicadas: 534
* Novo formato do Dataframe após .drop: 534 linhas

🏥 Investigando pacientes com múltiplas internações na base histórica:
===========================================================================
Número de pacientes únicos com mais de 1 registro na base: 9740

Top 5 pacientes com mais internações registradas:
name
michael williams    24
michael smith       23
robert smith        22
james brown         19
james smith         18
Name: count, dtype: int64